const puppeteer = require('puppeteer');

let searchArray = [
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
	'asus rog',
	'mx master 3',
	'asus',
	'asus laptop',
	'razer blade',
	'razer mouse',
	'razer keyboard',
	'razer mousepad',
	'razer touchpad',
	'razer tablet',
	'logitech',
	'LG 27" 27GP850 UltraGear',
];

(async () => {
	try {
		const browser = await puppeteer.connect({
			browserURL: 'http://localhost:9444',
		});

		const pages = await browser.pages();
		const page = pages[0];
		await page.setViewport({ width: 2048, height: 1024 });

		const searchBar = '.shopee-searchbar-input__input';
		const searchButton = '.shopee-searchbar__search-button';
		const shopeeUrl = 'https://shopee.com.my/';

		for (const searchText of searchArray) {
			// await page.goto(shopeeUrl); // Replace with the Shopee URL
			await page.waitForSelector(searchBar);
			await page.$eval(searchBar, input => (input.value = '')); // Clear input field
			await page.type(searchBar, searchText);
			await page.click(searchButton, { delay: 1000 });
			await page.waitForSelector('.shopee-search-item-result__item'); // Wait for search results

			// Click on the link in the first search result
			const linkSelector = '.shopee-search-item-result__item a[data-sqe="link"]';
			await page.waitForSelector(linkSelector);
			await page.click(linkSelector);

			console.log(`Clicked on the link in the first search result for: ${searchText}`);
		}
	} catch (error) {
		console.log('🚀 ~ file: index.js:27 ~ error:', error);
	}

	process.exit(0);
})();
